[server]
hostname = "localhost"
node_ip = "127.0.0.1"
offset="1"
server_role = "gateway-worker"
#default_cache_timeout = 0
#discard_empty_caches = false
#force_local_cache = false

#[apim.cache.gateway_token]
#enable = false

#[user_store.properties]
#CaseInsensitiveUsername = "false"
#IsBulkImportSupported = "false"

[database.local]
url = "jdbc:h2:./repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"

[[event_listener]]
id = "token_revocation"
type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
name = "org.wso2.is.notification.ApimOauthEventInterceptor"
order = 1
[event_listener.properties]
notification_endpoint = "https://localhost:${mgt.transport.https.port}/internal/data/v1/notify"
username = "${admin.username}"
password = "${admin.password}"
'header.X-WSO2-KEY-MANAGER' = "default"

[authentication.consent]
data_source = "jdbc/WSO2CarbonDB"


#[apim.cache.gateway_token]
#enable = true
#expiry_time = "900s"

#[apim.cache.resource]
#enable = true
#expiry_time = "60s"

#[apim.cache.km_token]
#enable = false
#expiry_time = "15m"

#[apim.cache.recent_apis]
#enable = false

#[apim.cache.scopes]
#enable = true

#[apim.cache.publisher_roles]
#enable = true

#[apim.cache.jwt_claim]
#enable = true
#expiry_time = "15m"

#[apim.cache.tags]
#expiry_time = "2m"

[user_store]
type = "database_unique_id"


[super_admin]
username = "admin"
password = "admin"
create_admin_account = true


[database.apim_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/devtprodapimgtdb?autoReconnect=true&amp;relaxAutoCommit=true&amp;useSSL=false&amp;"
username = "root"
password = "1qaz@WSX"

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/devtprodregdb?autoReconnect=true&amp;relaxAutoCommit=true&amp;useSSL=false&amp;"
username = "root"
password = "1qaz@WSX"

[database.user]
type = "mysql"
url = "jdbc:mysql://localhost:3306/devtproduserstoredb?autoReconnect=true&amp;relaxAutoCommit=true&amp;useSSL=false&amp;"
username = "root"
password = "1qaz@WSX"

[realm_manager]
data_source = "WSO2USER_DB"

[keystore.tls]
file_name =  "wso2carbon.jks"
type =  "JKS"
password =  "wso2carbon"
alias =  "wso2carbon"
key_password =  "wso2carbon"


# key manager implementation
[apim.key_manager]
service_url = "https://localhost:9445/services/"
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
type = "WSO2-IS"

# JWT Generation
[apim.jwt]
enable = true

[apim.cors]
allow_origins = "*"
allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","apikey", "testKey"]
allow_credentials = false

# Traffic Manager configurations
[apim.throttling]
enable_policy_deploy = false
enable_header_based_throttling = true
enable_jwt_claim_based_throttling = true
enable_query_param_based_throttling = true
throttle_decision_endpoints = ["tcp://localhost:5675"]

[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9614"]
traffic_manager_auth_urls = ["ssl://localhost:9714"]

[transport.https.sslHostConfig.properties]
protocols = "+TLSv1.1,+TLSv1.2"
